### ISSUE TITLE
False positive detection (crypto-miner IP addresses from DNS)

### ISSUE THREAD

**Issue by arudinskis** [falcosecurity/rules#62]
`mine.moneropool.com` DNS A and AAAA resolve to Cloudflare IP addresses. `status.dpd.lt` also resolves the same Cloudflare IP addresses and due to this rule `Detect outbound connections to common miner pool ports` is triggered false positively.

It seems that Falco resolves and periodically updates [crypto-miner IP addresses](https://github.com/falcosecurity/rules/blob/main/rules/falco_rules.yaml#L2844-L2912) from DNS. When a connect syscall occurs to one of those IP addresses it fires an alert. More details: https://falco.org/docs/rules/fd-sip-name/

Would it be possible to map a crypto miner domain with corresponding IP addresses? This way there shouldn’t be any false positives. Or are there other options on how to get rid of these false positives without creating exceptions?

**Comment by incertum** [comment]
Hi @arudinskis we have good news refactoring meaning a complete revamp in this regard is on the Falco Roadmap https://github.com/orgs/falcosecurity/projects/5. We may not be able to land it for Falco 0.36, because there are other competing priorities, but hopefully we have a better approach by Falco 0.37.

CC @loresuso

**Comment by loresuso** [comment]
Totally agree with @incertum! Things start moving in this regard!
